services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS:-rootpass}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: ".env"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS:-rootpass}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER:-root}:${MONGODB_PASS:-rootpass}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  auth:
    image: 'narfman0/nk-auth-docker:latest'
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      SECRET: ${SECRET}
      MONGODB_HOST: ${MONGODB_HOST:-mongo}
    build:
      context: ./auth
    ports:
      - 8080:8080
  backend:
    image: 'narfman0/nk-backend-docker:latest'
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      SECRET: ${SECRET}
      MONGODB_HOST: ${MONGODB_HOST:-mongo}
      UVICORN_RELOAD: ${UVICORN_RELOAD:-true}
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 7666:7666
    develop:
      watch:
        - path: ./backend/requirements.txt
          action: rebuild
        - path: ./shared/nk_shared
          action: sync
          target: /app/nk_shared
        - path: ./backend/nk
          action: sync
          target: /app/nk
        - path: ./data
          action: sync
          target: /data
