services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS:-rootpass}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: ".env"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS-rootpass}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER:-root}:${MONGODB_PASS-rootpass}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
