# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nk/proto/text_message.proto, nk/proto/message.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TextMessage(betterproto.Message):
    text: str = betterproto.string_field(1)


@dataclass
class Message(betterproto.Message):
    text_message: "TextMessage" = betterproto.message_field(1, group="payload")
