# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nk/proto/player_joined.proto, nk/proto/player_join_request.proto, nk/proto/player_left.proto, nk/proto/player_update.proto, nk/proto/text_message.proto, nk/proto/message.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerJoined(betterproto.Message):
    uuid: str = betterproto.string_field(1)


@dataclass
class PlayerJoinRequest(betterproto.Message):
    uuid: str = betterproto.string_field(1)


@dataclass
class PlayerLeft(betterproto.Message):
    uuid: str = betterproto.string_field(1)


@dataclass
class PlayerUpdate(betterproto.Message):
    uuid: str = betterproto.string_field(1)
    x: float = betterproto.float_field(2)
    y: float = betterproto.float_field(3)


@dataclass
class TextMessage(betterproto.Message):
    text: str = betterproto.string_field(1)


@dataclass
class Message(betterproto.Message):
    text_message: "TextMessage" = betterproto.message_field(1, group="payload")
    player_joined: "PlayerJoined" = betterproto.message_field(2, group="payload")
    player_left: "PlayerLeft" = betterproto.message_field(3, group="payload")
    player_join_request: "PlayerJoinRequest" = betterproto.message_field(
        4, group="payload"
    )
    player_update: "PlayerUpdate" = betterproto.message_field(5, group="payload")
